// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_K1j5f4jzugRsQfMZ_zbFf2x9Jh1OPME',
    appId: '1:707253409339:web:5799a5997c938f7739ae1e',
    messagingSenderId: '707253409339',
    projectId: 'travelify-599d4',
    authDomain: 'travelify-599d4.firebaseapp.com',
    databaseURL: 'https://travelify-599d4-default-rtdb.firebaseio.com',
    storageBucket: 'travelify-599d4.appspot.com',
    measurementId: 'G-5EENVM1675',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrWaQt4JT5vyzT_fEziTzRQ7VeLly0LJQ',
    appId: '1:707253409339:android:9cd4ab73d7b8da0439ae1e',
    messagingSenderId: '707253409339',
    projectId: 'travelify-599d4',
    databaseURL: 'https://travelify-599d4-default-rtdb.firebaseio.com',
    storageBucket: 'travelify-599d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyngMEeDkVTg80YTDQ1h_i1Pao-729jDk',
    appId: '1:707253409339:ios:d6a05fe16fabd4a439ae1e',
    messagingSenderId: '707253409339',
    projectId: 'travelify-599d4',
    databaseURL: 'https://travelify-599d4-default-rtdb.firebaseio.com',
    storageBucket: 'travelify-599d4.appspot.com',
    iosClientId: '707253409339-kla47fdet7o0rjm9oj7olp93lpqa8nn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.talabatApp',
  );
}
